- hosts: all
  become: yes

  tasks:
    - name: Geting .env file
      template:
        src: .env.template.j2
        dest: .env
        mode: '0644'  

    - name: Pulling redmine docker image
      community.docker.docker_image:
        name: redmine
        tag: latest
        source: pull
  
    - name: Running redmine docker container
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        env_file: .env
        published_ports:
          - "80:3000"
